DELETE FROM DEPT WHERE DEPTNO=50;


INSERT INTO DEPT VALUES (60,'MARKETING', 'SEOUL');


COMMIT;

SELECT DEPTNO, DNAME, LOC FROM DEPT;

SELECT E1.EMPNO, E1.ENAME, E1.JOB, E2.ENAME as mgr 
					    FROM EMP E1, EMP E2 
					   WHERE E1.MGR = E2.EMPNO AND DEPTNO=10;
                       
SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP E, SALGRADE S, DEPT D
WHERE E.DEPTNO = D.DEPTNO
  AND E.SAL BETWEEN LOSAL AND HISAL
  AND DNAME='';
                       
                
  
  DELETE FROM DEPT WHERE DEPTNO>40;
  
  
  
  	SELECT EMPNO, ENAME, SAL, RANK() OVER(ORDER BY sal DESC) AS RANK,
  DENSE_RANK() OVER(ORDER BY sal DESC) AS DENSE_RANK,
  ROW_NUMBER() OVER(ORDER BY sal DESC) AS ROW_NUMBER
FROM EMP;


SELECT * FROM DEPT;


UPDATE DEPT SET DNAME='IT', LOC='PUSAN'
WHERE DEPTNO=50;

DELETE DEPTNO FROM DEPT WHERE DEPTNO=50;

select * from dept;

delete from dept where deptno=60;