print("Hello, world!")
print(3)
print("Hello, world!")
print(3)
print("Hello, world!")
print(3)
print("Hello, world!")
print(3)
print("Hello, world!")
print(3)
print("Hello, world!")
print(3)
print("Hello, world!")
print(3)
