CREATE TABLE JOB (
    JNO NUMBER(2),
    JNAME VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_JOB PRIMARY KEY (JNO)    
);

CREATE TABLE PERSON (
    ID NUMBER(5),
    NAME VARCHAR2(30) NOT NULL,
    JNO NUMBER(2),
    KOR NUMBER(3) CHECK (KOR > 0) NOT NULL,
    ENG NUMBER(3) CHECK (ENG > 0) NOT NULL,
    MAT NUMBER(3) CHECK (MAT > 0) NOT NULL,
    CONSTRAINT PK_PERSON PRIMARY KEY (ID),
    CONSTRAINT FK_PERSON FOREIGN KEY (JNO)
    REFERENCES JOB(JNO)
);

ALTER TABLE PERSON RENAME COLUMN ID TO NO;

CREATE SEQUENCE SEQ_PERSON_NO
MAXVALUE 99999 NOCACHE;

INSERT INTO JOB VALUES(10,'배우');
INSERT INTO JOB VALUES(20,'배우');


-- 1번 기능 확인
INSERT INTO PERSON VALUES 
(SEQ_PERSON_NO.NEXTVAL, 
'정우성', (SELECT JNO FROM JOB WHERE JNAME='배우'), 90,80,81);

INSERT INTO PERSON VALUES (SEQ_PERSON_NO.NEXTVAL, '박세영', 10, 80,90,80);
INSERT INTO PERSON VALUES (SEQ_PERSON_NO.NEXTVAL, '배수지', 20, 20,90,90);
INSERT INTO PERSON VALUES (SEQ_PERSON_NO.NEXTVAL, '설현', 20, 95,95,95);
INSERT INTO PERSON VALUES (SEQ_PERSON_NO.NEXTVAL, '송혜교', 10, 100,100,100);



SELECT JNO FROM JOB WHERE JNAME='배우';

-- 1번 기능 확인
SELECT NO, NAME, JNO, KOR, ENG, MAT
FROM PERSON;

--2번 기능
SELECT ROWNUM AS RANK, A.*
FROM
(
    SELECT NAME ||'(' || NO || '번)' AS NAME , 
           JNAME, KOR, ENG, MAT, KORENGMAT SUM
      FROM PERSON P, JOB J
     WHERE P.JNO = J.JNO AND JNAME='배우'
     ORDER BY SUM DESC
) A;


--3번 기능
SELECT ROWNUM AS RANK, A.*
FROM
(
SELECT NAME ||'(' || NO || '번)' AS NAME , JNAME, KOR, ENG, MAT, KORENGMAT SUM
FROM PERSON P, JOB J
WHERE P.JNO = J.JNO 
ORDER BY SUM DESC
) A;

--4번 콤보박스에 넣을 직업리스트
SELECT JNAME FROM JOB;