DROP TABLE CUSTOMER;

DROP TABLE CUS_LEVEL;

CREATE TABLE CUS_LEVEL(
    LEVELNO NUMBER(1),
    LEVELNAME VARCHAR2(20) NOT NULL,
    LOW NUMBER(9) CHECK (LOW>=0) NOT NULL ,
    HIGH NUMBER(9) CHECK (HIGH>=0) NOT NULL ,
    CONSTRAINT PK_CUS_LEVEL PRIMARY KEY (LEVELNO)    
);

CREATE TABLE CUSTOMER(
    CID     NUMBER(6),
    CTEL    VARCHAR2(50) NOT NULL,
    CNAME   VARCHAR2(50) NOT NULL,    
    CPOINT  NUMBER(9) DEFAULT 1000 NOT NULL,
    CAMOUNT NUMBER(9) DEFAULT 0  NOT NULL,
    LEVELNO NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CID),
    CONSTRAINT FK_CUSTOMER_LEVELNO FOREIGN KEY (LEVELNO)
    REFERENCES CUS_LEVEL(LEVELNO)
);

DROP SEQUENCE SEQ_CUSTOMER_CID;

CREATE SEQUENCE SEQ_CUSTOMER_CID 
MAXVALUE 999999 NOCACHE NOCYCLE;

DELETE FROM CUS_LEVEL;

-- 더미 데이터 인서트
INSERT INTO CUS_LEVEL VALUES (1,'NORMAL',0000000,999999);
INSERT INTO CUS_LEVEL VALUES (2,'SILVER',1000000,1999999);
INSERT INTO CUS_LEVEL VALUES (3,'GOLD',2000000,2999999);
INSERT INTO CUS_LEVEL VALUES (4,'VIP',3000000,3999999);
INSERT INTO CUS_LEVEL VALUES (5,'VVIP',4000000,999999999);

SELECT * FROM CUS_LEVEL;

DELETE FROM CUSTOMER;

INSERT INTO CUSTOMER (CID,CTEL, CNAME ) VALUES (SEQ_CUSTOMER_CID.NEXTVAL, '010-9999-9999', '홍길동');
INSERT INTO CUSTOMER 
SELECT SEQ_CUSTOMER_CID.NEXTVAL, '010-8888-9999', '김길동', 1000, 5000000, 5 FROM DUAL;
INSERT INTO CUSTOMER 
SELECT SEQ_CUSTOMER_CID.NEXTVAL, '010-8888-8888', '박길동', 100000, 2500000, 3 FROM DUAL;



COMMIT;

SELECT * FROM CUSTOMER;

CREATE OR REPLACE VIEW VW_PRINT AS
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, 
       NVL(((SELECT LOW FROM CUS_LEVEL WHERE LEVELNO = A.LEVELNO+1)-CAMOUNT),0) AS NEXT
FROM CUSTOMER A, CUS_LEVEL B
WHERE CAMOUNT BETWEEN LOW AND HIGH;

SELECT * FROM VW_PRINT;

-- 0. 레벨 이름들
SELECT LEVELNAME FROM CUS_LEVEL ORDER BY LEVELNO;

-- 1. 아이디 검색
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, NEXT 
  FROM VW_PRINT WHERE CID=2;

-- 2. 폰자리 검색
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, NEXT 
  FROM VW_PRINT WHERE CTEL LIKE '%'||'9999';

-- 3. 고객 이름 검색
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, NEXT 
  FROM VW_PRINT WHERE CNAME = '박길동';
  
-- 4. 포인트로만 구매
UPDATE CUSTOMER SET CPOINT = CPOINT - 500 WHERE CID=1;

SELECT * FROM CUSTOMER;

-- 5. 물품구매
UPDATE CUSTOMER A
   SET CPOINT = CPOINT + 1000000*0.05, 
       CAMOUNT = CAMOUNT + 1000000,
       LEVELNO = (SELECT LEVELNO 
                  FROM CUS_LEVEL 
                 WHERE A.CAMOUNT+1000000 
               BETWEEN LOW AND HIGH)
 WHERE CID=3;


-- 6. 등급별 출력
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, NEXT  
  FROM VW_PRINT WHERE LEVELNAME='VVIP' ORDER BY CAMOUNT DESC;
  
-- 7. 전체 출력
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, LEVELNAME, NEXT  
  FROM VW_PRINT;

-- 8. 회원가입
INSERT INTO CUSTOMER (CID,CTEL, CNAME ) VALUES (SEQ_CUSTOMER_CID.NEXTVAL, '010-9999-9999', '홍길동');

-- 9. 번호수정
UPDATE CUSTOMER SET CTEL='010-8888-7777' WHERE CID=3;

SELECT * FROM CUSTOMER;

-- 10. 회원탈퇴
DELETE CUSTOMER WHERE CID=4;

