CREATE TABLE MAJOR (
    MNO NUMBER(2),
    MNAME VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_MAJOR PRIMARY KEY (MNO)    
);

DROP TABLE STUDENT;

CREATE TABLE STUDENT (
    SNO VARCHAR2(7),
    SNAME VARCHAR2(50) NOT NULL,
    MNO NUMBER(2),
    SCORE NUMBER(3) CHECK (SCORE >= 0 AND SCORE <= 100) NOT NULL,
    SEXPEL NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY (SNO),
    CONSTRAINT FK_STUDENT FOREIGN KEY (MNO)
    REFERENCES MAJOR(MNO),
    CONSTRAINT CHK_SEXPEL CHECK (SEXPEL=0 OR SEXPEL=1)     
);

INSERT INTO MAJOR VALUES (1, '빅데이터학');
INSERT INTO MAJOR VALUES (2, '경영정보학');
INSERT INTO MAJOR VALUES (3, '컴퓨터공학');
INSERT INTO MAJOR VALUES (4, '소프트웨어');
INSERT INTO MAJOR VALUES (5, '인공지능학');	
    
    
INSERT INTO STUDENT VALUES ('2021001','정우성',1,90	 ,0);
INSERT INTO STUDENT VALUES ('2021002','박세영',1,80	 ,0);
INSERT INTO STUDENT VALUES ('2021003','배수지',3,70	 ,0);
INSERT INTO STUDENT VALUES ('2021004','홍길동',4,95	 ,0);
INSERT INTO STUDENT VALUES ('2021005','송혜교',5,100 ,0);
INSERT INTO STUDENT VALUES ('2021006','홍철수',4,20  ,1);

INSERT INTO STUDENT VALUES ('2021007','정우성',2,30	 ,1);

COMMIT;


-- 1번 기능 
INSERT INTO STUDENT VALUES 
('2021001','정우성',(SELECT MNO FROM MAJOR WHERE MNAME='빅데이터학'),90	 ,0);

-- 2번 기능 
SELECT ROWNUM||'등' RANK, A.*
FROM (
    SELECT SNAME||'('||SNO||')' AS NAMENO, MNAME, SCORE
    FROM STUDENT S, MAJOR M
    WHERE S.MNO = M.MNO AND M.MNO=1
    ORDER BY SCORE DESC
) A;

-- 3번 기능
SELECT ROWNUM||'등' RANK, A.*
FROM (
    SELECT SNO, SNAME, MNAME, SCORE, SEXPEL
    FROM STUDENT S, MAJOR M
    WHERE S.MNO = M.MNO
      AND SEXPEL=0
    ORDER BY SCORE DESC
) A;

-- 4번 기능
SELECT ROWNUM||'등' RANK, A.*
FROM (
     SELECT SNO, SNAME, MNAME, SCORE, SEXPEL
    FROM STUDENT S, MAJOR M
    WHERE S.MNO = M.MNO
      AND SEXPEL=0
    ORDER BY SCORE DESC
) A;

-- 5번기능 학번검색
SELECT SNO, SNAME, MNAME, SCORE, SEXPEL
    FROM STUDENT S, MAJOR M
    WHERE S.MNO = M.MNO AND SNO='2021002';


-- 6번 기능 이름 검색
SELECT SNO, SNAME, MNAME, SCORE, SEXPEL
    FROM STUDENT S, MAJOR M
    WHERE S.MNO = M.MNO AND SNAME='배수지';

-- 7번 기능 전공 검색
SELECT SNO, SNAME, MNAME, SCORE, SEXPEL
    FROM STUDENT S, MAJOR M
    WHERE S.MNO = M.MNO 
      AND M.MNO = (SELECT MNO FROM MAJOR WHERE MNAME='소프트웨어');

-- 8번 업데이트
UPDATE STUDENT 
   SET SNAME='정우성', MNO=(SELECT MNO FROM MAJOR WHERE MNAME='경영정보학') ,
                   SCORE=90, SEXPEL=0
 WHERE SNO='2021001';

-- 8번 기능 학생 출력
SELECT SNO, SNAME, MNAME, SCORE, SEXPEL
    FROM STUDENT S, MAJOR M
    WHERE S.MNO = M.MNO;

SELECT * FROM STUDENT;