
SELECT ENAME, ROUND(SAL, - 3) FROM EMP; -- 단일행 함수

-- 그룹 함수 SUM, AVG, MIN, MAX, COUNT , STDDEV, VARIANCE
SELECT SUM(SAL) FROM EMP;   -- 그룹 함수

--그룹함수는 단일행과 같이 쓸 수 없음
SELECT ENAME, SUM(SAL) FROM EMP GROUP BY ENAME;

SELECT DEPTNO, SUM(SAL) FROM EMP GROUP BY DEPTNO;

SELECT AVG(SAL) FROM EMP;

SELECT COUNT(COMM) FROM EMP;

SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO;


SELECT AVG(SAL), SUM(SAL)/COUNT(SAL) FROM EMP;

-- 그룹함수는 NULL값을 제외
SELECT AVG(COMM), SUM(COMM), COUNT(COMM) FROM EMP;

SELECT ROUND(AVG(SAL)), SUM(SAL), MIN(SAL), MAX(SAL), ROUND(VARIANCE(SAL)), ROUND(STDDEV(SAL)), COUNT(SAL)
FROM EMP;

SELECT DEPTNO, AVG(SAL) AVGSAL
  FROM EMP
 GROUP BY DEPTNO
 ORDER BY DEPTNO, AVGSAL;
 

SELECT A.* 
  FROM EMP A
  WHERE (DEPTNO, HIREDATE) IN (SELECT DEPTNO, MIN(HIREDATE)  FROM EMP B GROUP BY DEPTNO);
  
SELECT MIN(HIREDATE) || ' 최초입사:' || TRUNC(SYSDATE - MIN(HIREDATE)), 
       MAX(HIREDATE) || ' 최근입사:' || TRUNC(SYSDATE - MAX(HIREDATE))
  FROM EMP;

SELECT MIN(HIREDATE) || ' 최초입사:' || TO_CHAR(TRUNC(SYSDATE - MIN(HIREDATE)),'99,999')||'일째' AS COL1, 
       MAX(HIREDATE) || ' 최근입사:' || TO_CHAR(TRUNC(SYSDATE - MAX(HIREDATE)),'99,999')||'일째' AS COL2
  FROM EMP;

SELECT AVG(SAL)
FROM EMP
WHERE DEPTNO=10;


-- GROUP BY절
SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO;


SELECT * 
FROM EMP
WHERE HIREDATE IN (SELECT MAX(HIREDATE) FROM EMP);


SELECT B.DNAME, JOB, COUNT(*), MAX(SAL) MAXSAL, MIN(SAL) MINSAL, ROUND(AVG(SAL),2) AVGSAL
FROM EMP A, DEPT B
WHERE A.DEPTNO = B.DEPTNO
GROUP BY DNAME, JOB
ORDER BY 1 ,2 ;

-- HAVING
SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO HAVING AVG(SAL) > 2000;


SELECT  DNAME, 
        DECODE(JOB, 'CLERK', SAL, 0) AS CLERK, 
        DECODE(JOB, 'MANAGER', SAL, 0) AS MANAGER, 
        DECODE(JOB, 'PRESIDENT', SAL, 0) AS PRESIDENT, 
        DECODE(JOB, 'ANALYST', SAL, 0) AS ANALYST, 
        DECODE(JOB, 'SALESMAN', SAL, 0) AS SALESMAN
  FROM EMP A, DEPT B
 WHERE A.DEPTNO = B.DEPTNO
 ORDER BY 1;


-- 3단계 : 합계추가
SELECT  NVL(DNAME,'합계'), 
        SUM(DECODE(JOB, 'CLERK', SAL, 0)) AS CLERK, 
        SUM(DECODE(JOB, 'MANAGER', SAL, 0)) AS MANAGER, 
        SUM(DECODE(JOB, 'PRESIDENT', SAL, 0)) AS PRESIDENT, 
        SUM(DECODE(JOB, 'ANALYST', SAL, 0)) AS ANALYST, 
        SUM(DECODE(JOB, 'SALESMAN', SAL, 0)) AS SALESMAN,
        SUM(SAL) AS
  FROM EMP A, DEPT B
 WHERE A.DEPTNO = B.DEPTNO
 GROUP BY CUBE(DNAME);
 
 
 

