DROP TABLE EMP01;

CREATE TABLE EMP01 AS SELECT * FROM EMP;

INSERT INTO EMP01 
SELECT EMPNO + TO_NUMBER(TO_CHAR(SYSTIMESTAMP,'FF3')),ENAME, JOB,MGR, HIREDATE + TO_NUMBER(TO_CHAR(SYSTIMESTAMP,'FF3')),SAL,COMM,DEPTNO FROM EMP01; -- 12번 수행 




SELECT COUNT(*) FROM EMP01;

INSERT INTO EMP01 (EMPNO, ENAME) VALUES (1111,'HONG'); --HONG 일부

--INSERT INTO EMP01 SELECT * FROM EMP01; -- 3번 수행(20만 ROW정도)

SELECT TO_CHAR(COUNT(*),'9,999,999') FROM EMP01;

SELECT * FROM EMP01 WHERE ENAME='HONG';


CREATE INDEX IDX_EMP_ENAME ON EMP01(ENAME);

SELECT * 
  FROM EMP01 
  WHERE ENAME='HONG'; -- 검색속도 엄청 느림


 -- insert 속도 엄청 느림

DROP INDEX  IDX_EMP_ENAME;




ALTER TABLE EMP01 MODIFY (EMPNO NUMBER(6));

